### ISSUE TITLE
NuxtJS Error

### ISSUE THREAD

**Issue by wodka** [2A5F/shadow#1]
The moment I try import the element it fails:

`app.js:507 Error: [nuxt] Error while mounting app: TypeError: Cannot read property 'install' of undefined
    at app.js:518`

**Comment by 2A5F** [comment]
I don't know much about nuxt.js
I have to try to use nuxt.js first

**Comment by wodka** [comment]
I added the module with yarn install and then created a small plugin for nuxt (a required step)

```js
// plugins/shadow.js
import Vue from 'vue'
import shadow from 'vue-shadow-dom'

export default () => {
  Vue.use(shadow)
}
```

and then in the nuxt.config.js I added the plugin.

-> then just using yields the error
