### ISSUE TITLE
Uncaught TypeError: o.defineComponent is not a function  

### ISSUE THREAD

**Issue by alenamm** [2A5F/shadow#130]
Hello!

When I am importing library to main.js, I get this error in console: Uncaught TypeError: o.defineComponent is not a function .

import shadow from 'vue-shadow-dom';

Could you please help?

**Comment by 2A5F** [comment]
Are you using vue 3 ?

**Comment by alenamm** [comment]
@2A5F  Sorry, my mistake, did not notice a note about version. I managed to make it working, now only need to figure out what to do with css :D
