### ISSUE TITLE
Strange behaviour for shadow-root with :static=true

### ISSUE THREAD

**Issue by brechtm** [2A5F/shadow#99]
```
<shadow-root :static=true>
    <div id="test1">TEST 1</div>
    <div id="test2">TEST 2</div>
    <div id="test3">TEST 3</div>
</shadow-root>
 ```

results in the second div dropping outside of the shadow root
```
<div>
    #shadow-root mode(open)
        <div id="test1">TEST 1</div>
        <div id="test1">TEST 3</div>
    <div id="test2">TEST 2</div>
</div>
 ```

**Comment by 2A5F** [comment]
I can't reproduce this

**Comment by brechtm** [comment]
In fact, all elements with an even end up outside of the shadow-root. Iteration over them might be taking two of them at the time or something?

**Comment by 2A5F** [comment]
what else did you do 
and what environment

loop is `for of`,  there should be no problems

**Comment by brechtm** [comment]
Sorry, I have stopped using shadow since shadow roots do not yet seem to be properly supported even in recent browser versions.
